import cn from "@iconify/icons-circle-flags/cn";
import hk from "@iconify/icons-circle-flags/hk";
import us from "@iconify/icons-circle-flags/us";
import chevronDown from "@iconify/icons-mdi/chevron-down";
import chevronUp from "@iconify/icons-mdi/chevron-up";
import close from "@iconify/icons-mdi/close";
import contentCopy from "@iconify/icons-mdi/content-copy";
import deleteSweep from "@iconify/icons-mdi/delete-sweep";
import download from "@iconify/icons-mdi/download";
import folderZip from "@iconify/icons-mdi/folder-zip";
import github from "@iconify/icons-mdi/github";
import imageOutline from "@iconify/icons-mdi/image-outline";
import translate from "@iconify/icons-mdi/translate";
import tune from "@iconify/icons-mdi/tune";
import { addIcon } from "@iconify/react/offline";

addIcon("mdi:tune", tune);
addIcon("mdi:close", close);
addIcon("mdi:github", github);
addIcon("mdi:image-outline", imageOutline);
addIcon("mdi:content-copy", contentCopy);
addIcon("mdi:download", download);
addIcon("mdi:chevron-up", chevronUp);
addIcon("mdi:chevron-down", chevronDown);
addIcon("mdi:delete-sweep", deleteSweep);
addIcon("mdi:folder-zip", folderZip);
addIcon("mdi:translate", translate);
addIcon("circle-flags:cn", cn);
addIcon("circle-flags:hk", hk);
addIcon("circle-flags:us", us);
